In [1]:
%matplotlib inline
%config InlineBackend.figure_format = 'retina'

In [2]:
from nbodykit.lab import *
from nbodykit.source.catalog import ArrayCatalog
from nbodykit import setup_logging, style

import os
import matplotlib.pyplot as plt
plt.style.use(style.notebook)

import numpy as np

In [3]:
setup_logging() # turn on logging to screen

In [4]:
#redshift = 0.5
#cosmo = cosmology.Planck15
LBox = 1024.0
Nparticles = 1024*1024*1024
print(Nparticles)

1073741824


In [5]:
# define download dir for the data to the current directory
download_dir = "../../../../halo_catalogues/F6/box1/27"
#download_dir = "/Users/mar/Research/Codigos/NagBody_pkg/NagBody_sources/colas/mglpicola_fofr/runs/mglpicola_fofr/B0256_P0256_M0256_testing/F5/box5001/output/."
#download_dir = "/Users/mar/Research/Codigos/NagBody_pkg/NagBody_sources/colas/mglpicola_fofr/runs/mglpicola_fofr/B0256_P0256_M0256/F5/box5001/output/."
#download_dir = "./gadget_data_27"

In [6]:
# NOTE: change this path if you downloaded the data somewhere else!
data_path = os.path.join(download_dir, 'Rockstar_M200c_F6_B1_B1024_NP1024_S27.dat')
#data_path = os.path.join(download_dir, 'snapshot_z0p000.*')
#data_path = os.path.join(download_dir, 'gadget.*')


# initialize the Gadget1 catalog objects for data and randoms
#data = Gadget1Catalog(data_path)

# Reading file
inputFile = np.loadtxt(data_path)

massvec=inputFile[:,2]
npvec=inputFile[:,7]
xvec=inputFile[:,8]
yvec=inputFile[:,9]
zvec=inputFile[:,10]
nval=massvec.shape[0]
npvecsum = np.sum(npvec)
print(nval)
print(npvecsum)
print(npvecsum/Nparticles)

#for i in range(0,nval):
#    xvec[i] = xvec[i]/LBox
#    yvec[i] = yvec[i]/LBox
#    zvec[i] = zvec[i]/LBox

arraya=np.array([xvec,yvec,zvec])
arrayb=np.transpose(arraya)
print arrayb

# generate the fake data
#data = numpy.empty(1024, dtype=[('Position', ('f8', 3)), ('Mass', 'f8')])
#data['Position'] = numpy.random.random(size=(1024, 3))
#data['Mass'] = numpy.random.random(size=1024)

data = numpy.empty(nval, dtype=[('Position', ('f8', 3)), ('Mass', 'f8')])
data['Position'] = arrayb
data['Mass'] = massvec


print(data['Mass'])
print(data['Position'])



2088610
272286591.0
0.2535866489633918
[[   5.05451   27.90979    7.1484 ]
 [   3.33114    2.02789    8.77102]
 [   6.93523   23.87998    3.54353]
 ...
 [1012.35187 1023.24255 1010.75012]
 [1018.56238 1010.28809 1012.22632]
 [1017.27716 1014.47455 1012.68018]]
[2.886e+12 3.665e+12 1.404e+12 ... 2.418e+12 1.560e+11 2.184e+12]
[[   5.05451   27.90979    7.1484 ]
 [   3.33114    2.02789    8.77102]
 [   6.93523   23.87998    3.54353]
 ...
 [1012.35187 1023.24255 1010.75012]
 [1018.56238 1010.28809 1012.22632]
 [1017.27716 1014.47455 1012.68018]]


We can analyze the available columns in the catalogs via the ``columns`` attribute:

In [7]:
#print('data columns = ', data.columns)

# save to a npy file
#numpy.save("npy-data.npy", data)
#
#rdata = numpy.load("npy-data.npy")
#
# initialize the catalog
#fdattmp = ArrayCatalog(rdata)

#print(fdattmp)
#print("columns = ", fdattmp.columns) # default Weight,Selection also present
#print("total size = ", fdattmp.csize)


fdata = ArrayCatalog({'Position' : data['Position'], 'Mass' : data['Mass'] })

print(fdata)
print("columns = ", fdata.columns) # default Weight,Selection also present
print("total size = ", fdata.csize)

ArrayCatalog(size=2088610)
('columns = ', ['Mass', 'Position', 'Selection', 'Value', 'Weight'])
('total size = ', 2088610)


In [13]:
ri = 0.01
rf = 100.0
Nr = 30
dr = (rf-ri)/int(Nr)
#redges = np.arange(ri,rf,dr)
redges = numpy.linspace(ri, rf, Nr+1) # 20 total bins
print(redges)
#MyBoxSize1 = data.attrs['MyBoxSize']
poleslist=[0,2,4]

[1.0000e-02 3.3430e+00 6.6760e+00 1.0009e+01 1.3342e+01 1.6675e+01
 2.0008e+01 2.3341e+01 2.6674e+01 3.0007e+01 3.3340e+01 3.6673e+01
 4.0006e+01 4.3339e+01 4.6672e+01 5.0005e+01 5.3338e+01 5.6671e+01
 6.0004e+01 6.3337e+01 6.6670e+01 7.0003e+01 7.3336e+01 7.6669e+01
 8.0002e+01 8.3335e+01 8.6668e+01 9.0001e+01 9.3334e+01 9.6667e+01
 1.0000e+02]


In [ ]:
tpc = SimulationBox3PCF(source=fdata,poles=poleslist,edges=redges,BoxSize=[LBox,LBox,LBox],periodic=True,position='Position')

[ 000705.54 ]   0: 10-17 09:16  SimulationBox3PCF INFO     using cpu grid decomposition: (1, 1, 1)
[ 000706.51 ]   0: 10-17 09:16  SimulationBox3PCF INFO     correlating 2088610 x 2088610 objects in total
[ 000706.51 ]   0: 10-17 09:16  SimulationBox3PCF INFO     correlating A x B = 2088610 x 2088610 objects (median) per rank
[ 000706.51 ]   0: 10-17 09:16  SimulationBox3PCF INFO     min A load per rank = 2088610
[ 000706.51 ]   0: 10-17 09:16  SimulationBox3PCF INFO     max A load per rank = 2088610
[ 000706.51 ]   0: 10-17 09:16  SimulationBox3PCF INFO     (even distribution would result in 2088610 x 2088610)
[ 000706.52 ]   0: 10-17 09:16  SimulationBox3PCF INFO     computing Ylm expressions...
[ 000708.71 ]   0: 10-17 09:16  SimulationBox3PCF INFO     ...done
[ 000709.21 ]   0: 10-17 09:16  SimulationBox3PCF INFO     0% done
[ 001421.83 ]   0: 10-17 09:28  SimulationBox3PCF INFO     10% done
[ 002147.66 ]   0: 10-17 09:40  SimulationBox3PCF INFO     20% done


In [ ]:
print(tpc)
print(tpc.D1D2)
print(tpc.R1R2)
print(tpc.corr)
tpcf=tpc.corr
print(tpcf.coords)

In [ ]:
rvec=tpcf['r']
tpcfvec=tpcf['corr'].real

#print(kvec[3])
#print(pkvec[3])

nr = rvec.shape[0]

print(nr)

tpcfa=np.array([rvec,tpcfvec])
tpcfb=np.transpose(tpcfa)
print tpcfb

np.savetxt('2pcf.dat',tpcfb,delimiter='\t',newline='\r\n')

In [ ]:
# print out the meta-data
for i in tpcf.attrs:
    print("%s = %s" %(i, str(tpcf.attrs[i])))

In [ ]:
fig1 = plt.figure()

# print the shot noise subtracted P(k)
plt.plot(tpcf['r'], tpcf['corr'])
#plt.loglog(Pk['k'], Pk['power'].real)


# format the axes
plt.xlabel(r"$r$ [$\mathrm{Mpc}/h$]")
plt.ylabel(r"$\xi$")
#plt.xlim(0.001, 0.6)
#plt.xlim(0.01, 10.0)
#plt.ylim(1,100000)

fig1.savefig("2pcf.pdf")